export type Product = {
  id: string;
  name: string;
  price: number;
  origin: string;
  category: string;
  maxQuantity?: number;
  images: string[];
};

export const products: Product[] = [
  {
    id: "yunomi-001",
    name: "煎茶碗 茶托セット（来客用）",
    price: 11000,
    origin: "益子焼（山口慶祐）",
    category: "湯呑・カップ",
    maxQuantity: 4,
    images:[ "/products/yunomi-001-1.jpg",
      "/products/yunomi-001-2.jpg",
      "/products/yunomi-001-3.jpg",
      "/products/yunomi-001-4.jpg",
      "/products/yunomi-001-5.jpg",]
  },
  {
    id: "coffee-001",
    name: "コーヒーカップ",
    price: 8800,
    origin: "益子焼（山口慶祐）",
    category: "湯呑・カップ",
    maxQuantity: 3,
    images:[ "/products/coffee-001-1.jpg",
      "/products/coffee-001-2.jpg",
      "/products/coffee-001-3.jpg",
      "/products/coffee-001-4.jpg",
      "/products/coffee-001-5.jpg",]
  },
  {
    id: "mug-001",
    name: "マグカップ",
    price: 7500,
    origin: "益子焼（山口慶祐）",
    category: "湯呑・カップ",
    maxQuantity: 2,
    images:[ "/products/mug-001-1.jpg",
      "/products/mug-001-2.jpg",
      "/products/mug-001-3.jpg",
      "/products/mug-001-4.jpg",
      "/products/mug-001-5.jpg",]
  },
  {
    id: "soup-001",
    name: "スープカップ",
    price: 9200,
    origin: "益子焼（山口慶祐）",
    category: "湯呑・カップ",
    maxQuantity: 2,
    images:[ "/products/soup-001-1.jpg",
      "/products/soup-001-2.jpg",
      "/products/soup-001-3.jpg",
      "/products/soup-001-4.jpg",
      "/products/soup-001-5.jpg",]
  },
  {
    id: "glass-001",
    name: "ガラスのコップ",
    price: 6000,
    origin: "作家の名前",
    category: "湯呑・カップ",
    maxQuantity: 4,
    images:[ "/products/glass-001-1.jpg",
      "/products/glass-001-2.jpg",
      "/products/glass-001-3.jpg",
      "/products/glass-001-4.jpg",
      "/products/glass-001-5.jpg",]
  },
  {
    id: "meshiwan-flat-001",
    name: "飯碗浅め",
    price: 6000,
    origin: "益子焼（山口慶祐）",
    category: "飯碗・丼",
    maxQuantity: 4,
    images:[ "/products/meshiwan-flat-001-1.jpg",
      "/products/meshiwan-flat-001-2.jpg",
      "/products/meshiwan-flat-001-3.jpg",
      "/products/meshiwan-flat-001-4.jpg",
      "/products/meshiwan-flat-001-5.jpg",]
  },
  {
    id: "meshiwan-deep-001",
    name: "飯碗深め",
    price: 6000,
    origin: "益子焼（山口慶祐）",
    category: "飯碗・丼",
    maxQuantity: 4,
    images:[ "/products/meshiwan-deep-001-1.jpg",
      "/products/meshiwan-deep-001-2.jpg",
      "/products/meshiwan-deep-001-3.jpg",
      "/products/meshiwan-deep-001-4.jpg",
      "/products/meshiwan-deep-001-5.jpg",]
  },
  {
    id: "ramen-001",
    name: "ラーメンどんぶり",
    price: 6000,
    origin: "益子焼（山口慶祐）",
    category: "飯碗・丼",
    maxQuantity: 4,
    images:[ "/products/ramen-001-1.jpg",
      "/products/ramen-001-2.jpg",
      "/products/ramen-001-3.jpg",
      "/products/ramen-001-4.jpg",
      "/products/ramen-001-5.jpg",]
  },
  {
    id: "plate-small-001",
    name: "小皿",
    price: 6000,
    origin: "益子焼（山口慶祐）",
    category: "皿・プレート",
    maxQuantity: 4,
    images:[ "/products/plate-smal-001-1.jpg",
      "/products/plate-smal-001-2.jpg",
      "/products/plate-smal-001-3.jpg",
      "/products/plate-smal-001-4.jpg",
      "/products/plate-smal-001-5.jpg",]
  },
  {
    id: "plate-medium-001",
    name: "中皿",
    price: 6000,
    origin: "益子焼（山口慶祐）",
    category: "皿・プレート",
    maxQuantity: 4,
    images:[ "/products/plate-medium-001-1.jpg",
      "/products/plate-medium-001-2.jpg",
      "/products/plate-medium-001-3.jpg",
      "/products/plate-medium-001-4.jpg",
      "/products/plate-medium-001-5.jpg",]
  },
  {
    id: "plate-large-001",
    name: "大皿（リム皿）",
    price: 6000,
    origin: "益子焼（山口慶祐）",
    category: "皿・プレート",
    maxQuantity: 4,
    images:[ "/products/plate-large-001-1.jpg",
      "/products/plate-large-001-2.jpg",
      "/products/plate-large-001-3.jpg",
      "/products/plate-large-001-4.jpg",
      "/products/plate-large-001-5.jpg",]
  },
  {
    id: "bowl-small-001",
    name: "小鉢",
    price: 6000,
    origin: "益子焼（山口慶祐）",
    category: "鉢・ボウル",
    maxQuantity: 4,
    images:[ "/products/bowl-small-001-1.jpg",
      "/products/bowl-small-001-2.jpg",
      "/products/bowl-small-001-3.jpg",
      "/products/bowl-small-001-4.jpg",
      "/products/bowl-small-001-5.jpg",]
  },
  {
    id: "bowl-medium-001",
    name: "中鉢",
    price: 6000,
    origin: "益子焼（山口慶祐）",
    category: "鉢・ボウル",
    maxQuantity: 4,
    images:[ "/products/bowl-medium-001-1.jpg",
      "/products/bowl-medium-001-2.jpg",
      "/products/bowl-medium-001-3.jpg",
      "/products/bowl-medium-001-4.jpg",
      "/products/bowl-medium-001-5.jpg",]
  },
  {
    id: "bowl-large-001",
    name: "大鉢",
    price: 6000,
    origin: "益子焼（山口慶祐）",
    category: "鉢・ボウル",
    maxQuantity: 4,
    images:[ "/products/bowl-large-001-1.jpg",
      "/products/bowl-large-001-2.jpg",
      "/products/bowl-large-001-3.jpg",
      "/products/bowl-large-001-4.jpg",
      "/products/bowl-large-001-5.jpg",]
  },
  {
    id: "flower-p-001",
    name: "水差し",
    price: 6000,
    origin: "益子焼（山口慶祐）",
    category: "花器",
    maxQuantity: 4,
    images:[ "/products/flower-p-001-1.jpg",
      "/products/flower-p-001-2.jpg",
      "/products/flower-p-001-3.jpg",
      "/products/flower-p-001-4.jpg",
      "/products/flower-p-001-5.jpg",]
  },
  {
    id: "flower-small-a-001",
    name: "一輪挿し",
    price: 6000,
    origin: "益子焼（山口慶祐）",
    category: "花器",
    maxQuantity: 4,
    images:[ "/products/flower-small-a-001-1.jpg",
      "/products/flower-small-a-001-2.jpg",
      "/products/flower-small-a-001-3.jpg",
      "/products/flower-small-a-001-4.jpg",
      "/products/flower-small-a-001-5.jpg",]
  },
  {
    id: "flower-small-b-002",
    name: "一輪挿し",
    price: 6000,
    origin: "益子焼（山口慶祐）",
    category: "花器",
    maxQuantity: 4,
    images:[ "/products/flower-small-b-001-1.jpg",
      "/products/flower-small-b-001-2.jpg",
      "/products/flower-small-b-001-3.jpg",
      "/products/flower-small-b-001-4.jpg",
      "/products/flower-small-b-001-5.jpg",]
  },
  {
    id: "teapot-001",
    name: "ティーポット",
    price: 6000,
    origin: "益子焼（山口慶祐）",
    category: "その他",
    maxQuantity: 4,
    images:[ "/products/teapot-001-1.jpg",
      "/products/teapot-001-2.jpg",
      "/products/teapot-001-3.jpg",
      "/products/teapot-001-4.jpg",
      "/products/teapot-001-5.jpg",]
  },
];